service: message-worker-service
frameworkVersion: '2'

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true

plugins: ['serverless-webpack', 'serverless-dotenv-plugin']

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ${env:REGION}
  apiGateway:
    minimumCompressionSize: 1024

functions:
  encryptMessage:
    handler: handler.encryptMessage
    events:
      - http:
          path: /encryptMessage
          method: post
          cors: true
